all::
	cd PhiLib; 	  make ;cd ..;\
	cd Helios;   	make ;cd ..;\
	cd JFractAll; make ;cd ..;\
	cd RPLogo;  	make ;cd ..;\






clean::
	cd PhiLib; 	  make clean;cd ..;\
	cd Helios;   	make clean;cd ..;\
	cd JFractAll; make clean;cd ..;\
	cd RPLogo;  	make clean;cd ..;\
