all:: PPgFrameChild.class PPgJFrame.class PPgField.class  PPgInputField.class PPgIntField.class  PPgFloatField.class   PPgCanvas.class PPgWinUtils.class   PPgTable.class PPgTableLine.class PPgGraphicsHelper.class PPgSelectBox.class PPgSliderDouble.class PPgSliderField.class PPgMenuGrid.class  PPgTrayIcon.class  JFontChooser.class FontComboBox.class



clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java


