all:: SimplePanel.class MyGamer.class Swarm.class SwarmMouse.class SwarmFlux.class Test.class DialogPref.class 
 

clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java
 
