all::   EnumFaction.class  Sprite.class ActorBase.class ActorLocation.class ActorMobil.class Gamer.class GamerHuman.class RenderBase.java PanelBox.class World.class	InterfaceDisplayGamer.class FrameGamer.class


clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java

