all::   SimplePanel.class GamerEvent.class MyGamer.class SwarmBoidMissile.class SwarmMouse.class  SwarmBoidMissile.java SwarmBoidFlux.class SwarmFlux.class SwarmAleaTarget.class Test.class DialogPref.class 
 

clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java
 
