all::   PPgExplosion.class  PPgSimpleExplosion.class   SwarmBoidFactory.class  SwarmBoid.class  Swarm.class  ParticleInterface.class ParticleFactoryInterface.class ParticleBase.class ParticleEngine.class ParticleSimple.class


clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java

