all:: FileChooserDemo2.class PPgImageFilter.class PPgImageUtils.class PPgImageFileView.class PPgImagePreview.class



clean::mv 
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java


