all::   GroundSquare.class GroundMap.class ProtoGroundSquare.class WorldRts.class Panel2D.class Render2D.class PanelMiniMap.class RenderMiniMap.class PanelResource.class RenderResource.class 

clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java
 
