all:: PPgMain.class PPgPref.class EdImgUtils.class EdImgInst.class PPgFrameEdImg.class PPgCanvasEdImg.class InterfaceEdImgListener.class      PPgLayerEdImg.class PPgLayerGroup.class DialogLayers.class    OpControler.class  OpHisto.class DialogHisto.class OpGraf.class OpGrafDropper.class OpGrafRot.class OpGrafCorrect.class OpGrafUtil.class OpGrafPencil.class  OpGrafSelZone.class OpGrafSelect.class OpGrafBrush.class  OpGrafEraser.class OpGrafFillColor.class  OpProps.class OpGrafFigure.class OpGrafGraduation.class OpLayers.class   PPgBrush.class  PPgMotif.class  DialogColor.class DialogImg.class SelectZone.class  SavConf.class DialogRescaleOp.class DialogPosterize.class DialogBase.class


clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java



